### PR TITLE
Fix blend shape handling.

### LINKED ISSUE #10: Importing takes too long
### Issue description

Importing takes too long.

https://share.firefox.dev/3EEnAw7

image

### Steps to reproduce

Import https://sketchfab.com/3d-models/facial-body-animated-party-m-0001-actorcore-aecb1b0c293a4185a91a532e635f3e6d

### Minimal reproduction project (For SDK or engine issues)

_No response_

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/ce2bd191ba89848ae1dc4f1cedf854846eda720b

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Macos, Godot 4.2 master.

### LINKED ISSUE #13: Blend shapes don't import correctly
### Issue description

Blend shapes import in-correctly.

### Steps to reproduce

1. Find a fbx with blend shapes.
2. Import with godot-ufbx
3. going from -1 to 1 blend shape values will scale the entire model

image

### Minimal reproduction project (For SDK or engine issues)

_No response_

### Using a released version?

https://github.com/V-Sekai/godot-ufbx/commit/e46cc52cce74310d14b8e77eb05e08944312a38c

### What OS? Any other relevant information? (godot-ufbx revision, Godot revision, System information)

Macos, Godot 4.2 master.

### PR DESCRIPTION
**Pull request by bqqbarbhg**
Should fix #13.

The core of the issue here is that geometry data in FBX is not indexed, so there is no way to map from the processed array mesh into blend shape offsets after `mesh_surface_tool->index()` is called. I assume that blend shapes are currently broken for non-indexed glTF meshes as well.

To fix this we need to retain vertex index information during this process, but as we have no extra geometry data channels to use currently I did a somewhat strange fix: Instead of storing vertex positions directly in `Mesh::ARRAY_VERTEX`, for meshes with blend shapes we store instead `Vector3(index & 0xffff, index >> 16, 0)`. This prevents the `index()` call from merging vertices that are in the same position but have potentially different blend offsets, but still allows merging identical vertices by index.

Afterwards it's easy to retrieve the vertex indices for generating the blend shape data. The real vertex positions are later patched in after blend shapes are read.

Edited:

Fixes: https://github.com/V-Sekai/godot-ufbx/issues/10
Fixes: https://github.com/V-Sekai/godot-ufbx/issues/13

### CODE REVIEW

**Comment by bqqbarbhg** [comment]
I also added a temporary local modification to ufbx to support normals in blend shapes, I'll add it to mainline ufbx with some tests soon.

**Comment by fire** [comment]
The normals are broken. Maybe axis conversion?

https://github.com/V-Sekai/godot-ufbx/assets/32321/5a187b4c-6a48-4887-89a9-a02816a46d56

**Comment by bqqbarbhg** [comment]
Shouldn't be it's local space, I'll take a look with that model!

**Comment by bqqbarbhg** [comment]
Turns out the normals were offsets as well (which is not too surprising), they feel a bit too strong in this model so not 100% sure what's going on but they look roughly correct at least.

**Comment by fire** [comment]
`array[Mesh::ARRAY_NORMAL] = _decode_vertex_attrib_vec3(fbx_mesh->vertex_tangent, indices);`

Noticed this bug.

**Comment by bqqbarbhg** [comment]
Whelp how did that happen, awkward copy-paste mistake from me, I'll fix it in this PR and see if it helps.

**Comment by fire** [comment]
Forgot to mention Tangent is a vector4/plane/color.

See the other uses of ARRAY_TANGENT

**Comment by bqqbarbhg** [comment]
Oh it contains the bitangent sign as well?

**Comment by fire** [comment]
See https://godotengine.org/article/fixing-tangents-accurate-normal-maps/

**Comment by fire** [comment]
> To save on space Godot uses the approach where only the tangents are store and bi-tangents are calculated by combining them with the normal vector. For this a direction flag is also included with each tangent.

**Comment by bqqbarbhg** [comment]
Yeah that's what I expected, I'll fix it!

File: fbx_document.cpp [hunk 1]
```diff
@@ -1791,31 +1818,49 @@ Error FBXDocument::_parse_meshes(Ref<FBXState> p_state) {
...
+							const int size = src_varr.size();
+							ERR_FAIL_COND_V(size == 0, ERR_PARSE_ERROR);
+							{
+								varr.resize(size);
+								narr.resize(size);
+
+								Vector3 *w_varr = varr.ptrw();
+								Vector3 *w_narr = narr.ptrw();
+								const Vector3 *r_varr = src_varr.ptr();
+								const Vector3 *r_narr = src_narr.ptr();
```
Comment (fire) [inline fbx_document.cpp:1865]:
```suggestion
```
This variable is unused?

File: thirdparty/ufbx/ufbx.c [hunk 2]
```diff
@@ -26524,18 +26524,25 @@ ufbx_abi ufbxi_noinline ufbx_matrix ufbx_catch_get_skin_vertex_matrix(ufbx_panic
 	return mat;
 }
 
-ufbx_abi ufbxi_noinline ufbx_vec3 ufbx_get_blend_shape_vertex_offset(const ufbx_blend_shape *shape, size_t vertex)
+ufbx_abi ufbxi_noinline uint32_t ufbx_get_blend_shape_offset_index(const ufbx_blend_shape *shape, size_t vertex)
 {
 	ufbx_assert(shape);
-	if (!shape) return ufbx_zero_vec3;
+	if (!shape) return UFBX_NO_INDEX;
```
Comment (fire) [inline thirdparty/ufbx/ufbx.c:26530]: Code style.

We always use curly braces.

Comment (fire) [reply thirdparty/ufbx/ufbx.c:26530]: Oops this is in ufbx.

File: fbx_document.cpp (hunk 1 above)
Comment (bqqbarbhg) [reply fbx_document.cpp:1865]: Whoops, I read straight from `src_narr` instead. I think this is just an optimization in the original source that I kept.

**Comment by fire** [comment]
When we're ready, we can rebase to one commit and merge. The reasoning for one commit is we ran into a detour in the middle of the patch series.

**Comment by bqqbarbhg** [comment]
Sure, do you mind if I add temporary animation support here as well while I'm at it?

**Comment by fire** [comment]
Want me to merge this in first? 

I can do it promptly. 

Then you can start on temporary animation support.

**Comment by bqqbarbhg** [comment]
Sure thing! I'm still sorting some unrelated stuff out for a while before I could start.
